{
    "name": "Project Task Gantt View",
    "summary": "Agrega una vista de Gantt para las tareas de proyectos.",
    "description": """Este módulo añade una vista de Gantt dedicada para gestionar las tareas del módulo de proyectos en Odoo.""",
    "version": "16.0.1.0.0",
    "author": "Generated by ChatGPT",
    "website": "https://www.example.com",
    "category": "Project",
    "depends": ["project", "web_gantt"],
    "data": [
        "views/project_task_gantt_views.xml"
    ],
    "application": False,
    "license": "LGPL-3"
}
